{
  "cveId": "CVE-2025-3121",
  "eventName": "Initial Analysis",
  "cveChangeId": "28F323DE-94C6-4897-AFCD-8FBB17084215",
  "sourceIdentifier": "nvd@nist.gov",
  "created": "2025-05-27T18:29:00.143",
  "details": [
    {
      "action": "Added",
      "type": "CVSS V3.1",
      "newValue": "AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
    },
    {
      "action": "Added",
      "type": "CPE Configuration",
      "newValue": "OR\n          *cpe:2.3:a:linuxfoundation:pytorch:2.6.0:-:*:*:*:python:*:*"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "VulDB: https://github.com/pytorch/pytorch/issues/149800 Types: Issue Tracking, Vendor Advisory"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "VulDB: https://github.com/pytorch/pytorch/issues/149800#issue-2940240700 Types: Issue Tracking, Vendor Advisory"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "VulDB: https://vuldb.com/?ctiid.303012 Types: Permissions Required, VDB Entry"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "VulDB: https://vuldb.com/?id.303012 Types: Third Party Advisory, VDB Entry"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "VulDB: https://vuldb.com/?submit.525049 Types: Exploit, Third Party Advisory, VDB Entry"
    }
  ]
}