{
  "cveId": "CVE-2025-48459",
  "eventName": "New CVE Received",
  "cveChangeId": "D8AA0439-72EB-4440-8345-49F573879EC0",
  "sourceIdentifier": "security@apache.org",
  "created": "2025-09-24T08:15:32.810",
  "details": [
    {
      "action": "Added",
      "type": "Description",
      "newValue": "Deserialization of Untrusted Data vulnerability in Apache IoTDB.\n\nThis issue affects Apache IoTDB: from 1.0.0 before 2.0.5.\n\nUsers are recommended to upgrade to version 2.0.5, which fixes the issue."
    },
    {
      "action": "Added",
      "type": "CWE",
      "newValue": "CWE-502"
    },
    {
      "action": "Added",
      "type": "Reference",
      "newValue": "https://lists.apache.org/thread/mr84n19nv8d0bmcrfsj3mm5ff5qn4q2f"
    }
  ]
}