{
  "cveId": "CVE-2018-25111",
  "eventName": "New CVE Received",
  "cveChangeId": "9BF80F3C-DC02-468E-BBB5-9812C7EFB105",
  "sourceIdentifier": "cve@mitre.org",
  "created": "2025-05-31T01:15:19.123",
  "details": [
    {
      "action": "Added",
      "type": "Description",
      "newValue": "django-helpdesk before 1.0.0 allows Sensitive Data Exposure because of os.umask(0) in models.py."
    },
    {
      "action": "Added",
      "type": "CVSS V3.1",
      "newValue": "AV:L/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N"
    },
    {
      "action": "Added",
      "type": "CWE",
      "newValue": "CWE-277"
    },
    {
      "action": "Added",
      "type": "Reference",
      "newValue": "https://github.com/django-helpdesk/django-helpdesk/issues/591"
    },
    {
      "action": "Added",
      "type": "Reference",
      "newValue": "https://github.com/django-helpdesk/django-helpdesk/pull/1120"
    },
    {
      "action": "Added",
      "type": "Reference",
      "newValue": "https://github.com/django-helpdesk/django-helpdesk/releases/tag/v1.0.0"
    }
  ]
}