{
  "cveId": "CVE-2025-61912",
  "eventName": "New CVE Received",
  "cveChangeId": "FB6B7F1E-8B49-4609-A2A4-70E7CC3B364E",
  "sourceIdentifier": "security-advisories@github.com",
  "created": "2025-10-10T22:15:37.637",
  "details": [
    {
      "action": "Added",
      "type": "Description",
      "newValue": "python-ldap is a lightweight directory access protocol (LDAP) client API for Python. In versions prior to 3.4.5, ldap.dn.escape_dn_chars() escapes \\x00 incorrectly by emitting a backslash followed by a literal NUL byte instead of the RFC-4514 hex form \\00. Any application that uses this helper to construct DNs from untrusted input can be made to consistently fail before a request is sent to the LDAP server (e.g., AD), resulting in a client-side denial of service. Version 3.4.5 contains a patch for the issue."
    },
    {
      "action": "Added",
      "type": "CVSS V4.0",
      "newValue": "AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:N/VA:L/SC:N/SI:N/SA:N/E:P/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X"
    },
    {
      "action": "Added",
      "type": "CWE",
      "newValue": "CWE-116"
    },
    {
      "action": "Added",
      "type": "CWE",
      "newValue": "CWE-170"
    },
    {
      "action": "Added",
      "type": "Reference",
      "newValue": "https://github.com/python-ldap/python-ldap/commit/6ea80326a34ee6093219628d7690bced50c49a3f"
    },
    {
      "action": "Added",
      "type": "Reference",
      "newValue": "https://github.com/python-ldap/python-ldap/releases/tag/python-ldap-3.4.5"
    },
    {
      "action": "Added",
      "type": "Reference",
      "newValue": "https://github.com/python-ldap/python-ldap/security/advisories/GHSA-p34h-wq7j-h5v6"
    }
  ]
}