{
  "cveId": "CVE-2025-61783",
  "eventName": "New CVE Received",
  "cveChangeId": "4A264282-8B37-4D36-A981-309F77480C8E",
  "sourceIdentifier": "security-advisories@github.com",
  "created": "2025-10-09T21:15:40.127",
  "details": [
    {
      "action": "Added",
      "type": "Description",
      "newValue": "Python Social Auth is a social authentication/registration mechanism. In versions prior to 5.6.0, upon authentication, the user could be associated by e-mail even if the `associate_by_email` pipeline was not included. This could lead to account compromise when a third-party authentication service does not validate provided e-mail addresses or doesn't require unique e-mail addresses. Version 5.6.0 contains a patch. As a workaround, review the authentication service policy on e-mail addresses; many will not allow exploiting this vulnerability."
    },
    {
      "action": "Added",
      "type": "CVSS V4.0",
      "newValue": "AV:N/AC:H/AT:N/PR:N/UI:N/VC:L/VI:L/VA:N/SC:L/SI:L/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X"
    },
    {
      "action": "Added",
      "type": "CWE",
      "newValue": "CWE-303"
    },
    {
      "action": "Added",
      "type": "Reference",
      "newValue": "https://github.com/python-social-auth/social-app-django/commit/10c80e2ebabeccd4e9c84ad0e16e1db74148ed4c"
    },
    {
      "action": "Added",
      "type": "Reference",
      "newValue": "https://github.com/python-social-auth/social-app-django/issues/220"
    },
    {
      "action": "Added",
      "type": "Reference",
      "newValue": "https://github.com/python-social-auth/social-app-django/issues/231"
    },
    {
      "action": "Added",
      "type": "Reference",
      "newValue": "https://github.com/python-social-auth/social-app-django/issues/634"
    },
    {
      "action": "Added",
      "type": "Reference",
      "newValue": "https://github.com/python-social-auth/social-app-django/pull/803"
    },
    {
      "action": "Added",
      "type": "Reference",
      "newValue": "https://github.com/python-social-auth/social-app-django/security/advisories/GHSA-wv4w-6qv2-qqfg"
    }
  ]
}