{
  "cveId": "CVE-2020-36820",
  "eventName": "New CVE Received",
  "cveChangeId": "2E5FC084-BF6F-4D36-BE2B-CB86F6993D96",
  "sourceIdentifier": "416baaa9-dc9f-4396-8d5f-8c081fb06d67",
  "created": "2025-09-16T16:15:38.887",
  "details": [
    {
      "action": "Added",
      "type": "Description",
      "newValue": "Rejected reason: ** REJECT ** DO NOT USE THIS CVE RECORD. ConsultIDs: none. Reason: This record was in a CNA pool that was not assigned to any issues during 2020. Notes: none."
    }
  ]
}