{
  "cveId": "CVE-2024-31580",
  "eventName": "Initial Analysis",
  "cveChangeId": "4E0FA84E-4452-44F5-B780-895B3ED87662",
  "sourceIdentifier": "nvd@nist.gov",
  "created": "2025-06-10T17:38:16.883",
  "details": [
    {
      "action": "Added",
      "type": "CPE Configuration",
      "newValue": "OR\n          *cpe:2.3:a:linuxfoundation:pytorch:*:*:*:*:*:python:*:* versions up to (excluding) 2.2.0"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "CVE: https://gist.github.com/1047524396/038c78f2f007345e6f497698ace2aa3d Types: Third Party Advisory"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "MITRE: https://gist.github.com/1047524396/038c78f2f007345e6f497698ace2aa3d Types: Third Party Advisory"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "CVE: https://github.com/pytorch/pytorch/commit/b5c3a17c2c207ebefcb85043f0cf94be9b2fef81 Types: Patch"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "MITRE: https://github.com/pytorch/pytorch/commit/b5c3a17c2c207ebefcb85043f0cf94be9b2fef81 Types: Patch"
    }
  ]
}