{
  "cveId": "CVE-2019-25209",
  "eventName": "New CVE Received",
  "cveChangeId": "EF502A4D-A002-4371-9A51-EE79E592C8F4",
  "sourceIdentifier": "416baaa9-dc9f-4396-8d5f-8c081fb06d67",
  "created": "2025-09-16T16:15:36.960",
  "details": [
    {
      "action": "Added",
      "type": "Description",
      "newValue": "Rejected reason: ** REJECT ** DO NOT USE THIS CVE RECORD. ConsultIDs: none. Reason: This record was in a CNA pool that was not assigned to any issues during 2019. Notes: none."
    }
  ]
}