{
  "cveId": "CVE-2019-25200",
  "eventName": "New CVE Received",
  "cveChangeId": "35271CE7-0DE1-4E47-895B-E547A105AEB1",
  "sourceIdentifier": "416baaa9-dc9f-4396-8d5f-8c081fb06d67",
  "created": "2025-09-16T16:15:36.357",
  "details": [
    {
      "action": "Added",
      "type": "Description",
      "newValue": "Rejected reason: ** REJECT ** DO NOT USE THIS CVE RECORD. ConsultIDs: none. Reason: This record was in a CNA pool that was not assigned to any issues during 2019. Notes: none."
    }
  ]
}