{
  "cveId": "CVE-2025-55557",
  "eventName": "Initial Analysis",
  "cveChangeId": "9B89228F-1101-4326-9B29-173857B45A9F",
  "sourceIdentifier": "nvd@nist.gov",
  "created": "2025-10-03T18:07:23.250",
  "details": [
    {
      "action": "Added",
      "type": "CVSS V3.1",
      "newValue": "AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    },
    {
      "action": "Added",
      "type": "CWE",
      "newValue": "NVD-CWE-noinfo"
    },
    {
      "action": "Added",
      "type": "CPE Configuration",
      "newValue": "\nOR\n          *cpe:2.3:a:linuxfoundation:pytorch:*:*:*:*:*:python:*:* versions up to (including) 2.7.0"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "MITRE: https://gist.github.com/shaoyuyoung/0e7d2a586297ae9c8ed14d8706749efc Types: Third Party Advisory"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "CISA-ADP: https://github.com/pytorch/pytorch/issues/151738 Types: Issue Tracking"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "MITRE: https://github.com/pytorch/pytorch/issues/151738 Types: Issue Tracking"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "MITRE: https://github.com/pytorch/pytorch/pull/151931 Types: Issue Tracking, Patch"
    }
  ]
}