{
  "cveId": "CVE-2022-50377",
  "eventName": "CVE Modified",
  "cveChangeId": "13ED28CD-2C56-413A-B8ED-7665672E0EC0",
  "sourceIdentifier": "416baaa9-dc9f-4396-8d5f-8c081fb06d67",
  "created": "2025-09-19T16:15:40.350",
  "details": [
    {
      "action": "Changed",
      "type": "Description",
      "oldValue": "In the Linux kernel, the following vulnerability has been resolved:\n\next4: check and assert if marking an no_delete evicting inode dirty\n\nIn ext4_evict_inode(), if we evicting an inode in the 'no_delete' path,\nit cannot be raced by another mark_inode_dirty(). If it happens,\nsomeone else may accidentally dirty it without holding inode refcount\nand probably cause use-after-free issues in the writeback procedure.\nIt's indiscoverable and hard to debug, so add an WARN_ON_ONCE() to\ncheck and detect this issue in advance.",
      "newValue": "Rejected reason: This CVE ID has been rejected or withdrawn by its CVE Numbering Authority."
    },
    {
      "action": "Removed",
      "type": "Reference",
      "oldValue": "kernel.org: https://git.kernel.org/stable/c/0c026f975d24701766cf4ac63995ead9f6d57a59"
    },
    {
      "action": "Removed",
      "type": "Reference",
      "oldValue": "kernel.org: https://git.kernel.org/stable/c/318cdc822c63b6e2befcfdc2088378ae6fa18def"
    },
    {
      "action": "Removed",
      "type": "Reference",
      "oldValue": "kernel.org: https://git.kernel.org/stable/c/9020f56a3cad1c97b81c7dab2aa67027b59c8f73"
    },
    {
      "action": "Removed",
      "type": "Reference",
      "oldValue": "kernel.org: https://git.kernel.org/stable/c/91009e361e8cb2cbd1dc9496cb5fb4f8de3f4b11"
    },
    {
      "action": "Removed",
      "type": "Reference",
      "oldValue": "kernel.org: https://git.kernel.org/stable/c/f1ec687ebd1bf146333955b7e209d21508c3ba9f"
    }
  ]
}