{
  "cveId": "CVE-2025-8813",
  "eventName": "CVE Modified",
  "cveChangeId": "04245820-0450-4F9C-8820-CFEC8ABA9944",
  "sourceIdentifier": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
  "created": "2025-08-12T20:15:33.330",
  "details": [
    {
      "action": "Added",
      "type": "Reference",
      "newValue": "https://github.com/atjiu/pybbs/issues/210"
    },
    {
      "action": "Added",
      "type": "Reference",
      "newValue": "https://github.com/atjiu/pybbs/issues/210#issue-3256474679"
    },
    {
      "action": "Added",
      "type": "Reference",
      "newValue": "https://github.com/atjiu/pybbs/issues/210#issuecomment-3134906856"
    }
  ]
}