{
  "cveId": "CVE-2025-8814",
  "eventName": "CVE Modified",
  "cveChangeId": "9277DDB6-C6EB-4881-9F0F-75860CB302D6",
  "sourceIdentifier": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
  "created": "2025-08-12T20:15:33.450",
  "details": [
    {
      "action": "Added",
      "type": "Reference",
      "newValue": "https://github.com/atjiu/pybbs/issues/211"
    },
    {
      "action": "Added",
      "type": "Reference",
      "newValue": "https://github.com/atjiu/pybbs/issues/211#issue-3256483043"
    },
    {
      "action": "Added",
      "type": "Reference",
      "newValue": "https://github.com/atjiu/pybbs/issues/211#issuecomment-3134960777"
    }
  ]
}