{
  "cveId": "CVE-2025-2999",
  "eventName": "Initial Analysis",
  "cveChangeId": "A5579E5B-A743-4E63-9B0C-7CF5DC918972",
  "sourceIdentifier": "nvd@nist.gov",
  "created": "2025-05-29T15:53:46.950",
  "details": [
    {
      "action": "Added",
      "type": "CPE Configuration",
      "newValue": "OR\n          *cpe:2.3:a:linuxfoundation:pytorch:2.6.0:-:*:*:*:python:*:*"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "VulDB: https://github.com/pytorch/pytorch/issues/149622 Types: Issue Tracking, Vendor Advisory"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "VulDB: https://github.com/pytorch/pytorch/issues/149622#issue-2935495265 Types: Issue Tracking, Vendor Advisory"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "VulDB: https://vuldb.com/?ctiid.302048 Types: Permissions Required, VDB Entry"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "VulDB: https://vuldb.com/?id.302048 Types: Third Party Advisory, VDB Entry"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "VulDB: https://vuldb.com/?submit.524198 Types: Third Party Advisory, VDB Entry"
    }
  ]
}