{
  "cveId": "CVE-2025-2998",
  "eventName": "Initial Analysis",
  "cveChangeId": "7DA8BD1D-7636-4C2E-8085-078EEB8001BC",
  "sourceIdentifier": "nvd@nist.gov",
  "created": "2025-05-29T15:53:57.197",
  "details": [
    {
      "action": "Added",
      "type": "CPE Configuration",
      "newValue": "OR\n          *cpe:2.3:a:linuxfoundation:pytorch:2.6.0:-:*:*:*:python:*:*"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "VulDB: https://github.com/pytorch/pytorch/issues/149622 Types: Issue Tracking, Vendor Advisory"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "VulDB: https://github.com/pytorch/pytorch/issues/149622#issue-2935495265 Types: Issue Tracking, Vendor Advisory"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "VulDB: https://vuldb.com/?ctiid.302047 Types: Permissions Required, VDB Entry"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "VulDB: https://vuldb.com/?id.302047 Types: Third Party Advisory, VDB Entry"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "VulDB: https://vuldb.com/?submit.524151 Types: Third Party Advisory, VDB Entry"
    }
  ]
}