{
  "cveId": "CVE-2022-35274",
  "eventName": "New CVE Received",
  "cveChangeId": "627D1665-527E-46A6-A926-C06B5859E13B",
  "sourceIdentifier": "secure@intel.com",
  "created": "2025-05-28T19:15:28.813",
  "details": [
    {
      "action": "Added",
      "type": "Description",
      "newValue": "Rejected reason: This CVE ID has been rejected or withdrawn by its CVE Numbering Authority because it is Unused"
    }
  ]
}